export interface Court {
  slug: string;
  name: string;
  type: "indoor" | "outdoor";
  address: string;
  city: string;
  zip: string;
  coordinates: { lat: number; lng: number };
  courtCount: number;
  surface: string;
  amenities: string[];
  hours: string;
  website?: string;
  phone?: string;
  notes?: string;
  hubGroupSlug?: string;
  featured?: boolean;
  image?: string;
}

const IMG_MULTICOURT = "/images/courts/courts-complex-multicourt-01.jpg";
const IMG_DAWN = "/images/courts/courts-dawn-mist-04.jpg";

export function getCourtImage(court: Pick<Court, "type" | "courtCount" | "image">): string {
  if (court.image) return court.image;
  if (court.type === "outdoor" && court.courtCount >= 4) return IMG_MULTICOURT;
  return IMG_DAWN;
}

export const courts: Court[] = [
  // ─── Outdoor — free public, dedicated ─────────────────────────────
  {
    slug: "bauer-drive-local-park",
    name: "Bauer Drive Local Park",
    type: "outdoor",
    address: "14536 Bauer Drive",
    city: "Rockville",
    zip: "20853",
    coordinates: { lat: 39.0920, lng: -77.1220 },
    courtCount: 6,
    surface: "Dedicated lighted pickleball courts",
    amenities: ["Lights", "Parking"],
    hours: "Dawn to dusk. Lights available evenings.",
    website: "https://montgomeryparks.org/parks-and-trails/bauer-drive-local-park/",
    notes: "Free. Six dedicated lighted courts — Montgomery Parks' first dedicated pickleball facility (opened October 2021). Popular morning and evening open play. First come, first served.",
    featured: true,
  },
  {
    slug: "east-norbeck-local-park",
    name: "East Norbeck Local Park",
    type: "outdoor",
    address: "3131 Norbeck Road",
    city: "Silver Spring",
    zip: "20906",
    coordinates: { lat: 39.0922, lng: -77.0801 },
    courtCount: 6,
    surface: "Dedicated lighted pickleball courts",
    amenities: ["Lights", "Parking"],
    hours: "Dawn to dusk. Lights available until 11pm.",
    website: "https://montgomeryparks.org/new-pickleball-courts-open-at-east-norbeck-local-park/",
    notes: "Free. Six dedicated lighted courts. M-NCPPC's flagship pickleball hub since November 2024. First come, first served.",
    featured: true,
  },
  {
    slug: "mattie-stepanek-park",
    name: "Mattie Stepanek Park",
    type: "outdoor",
    address: "1800 Piccard Drive",
    city: "Rockville",
    zip: "20850",
    coordinates: { lat: 39.0892, lng: -77.1856 },
    courtCount: 4,
    surface: "Dedicated lighted pickleball courts",
    amenities: ["Lights", "Parking", "Restrooms", "Playground"],
    hours: "Dawn to dusk",
    website: "https://www.rockvillemd.gov/places/mattie-j-t-stepanek-park/",
    notes: "Free. Four dedicated lighted courts. Open play available — popular with morning and evening players.",
    featured: true,
  },
  {
    slug: "olney-mill-neighborhood-park",
    name: "Olney Mill Neighborhood Park",
    type: "outdoor",
    address: "19600 Charline Manor Rd",
    city: "Olney",
    zip: "20832",
    coordinates: { lat: 39.1683, lng: -77.0683 },
    courtCount: 4,
    surface: "Dedicated lighted pickleball courts",
    amenities: ["Lights", "Parking"],
    hours: "Dawn to dusk. Lights available evenings.",
    notes: "Free. Four lined and lit dedicated courts — the go-to spot for pickleball players in Olney and northern Montgomery County.",
  },
  {
    slug: "broome-athletic-park",
    name: "Broome Athletic Park",
    type: "outdoor",
    address: "751 Twinbrook Parkway",
    city: "Rockville",
    zip: "20851",
    coordinates: { lat: 39.0735, lng: -77.1136 },
    courtCount: 4,
    surface: "Dedicated pickleball courts",
    amenities: ["Parking"],
    hours: "Dawn to dusk",
    website: "https://www.rockvillemd.gov/2313/Pickleball",
    notes: "Free. Four dedicated official pickleball courts run by the City of Rockville.",
  },
  {
    slug: "seven-locks-local-park",
    name: "Seven Locks Local Park",
    type: "outdoor",
    address: "6922 Seven Locks Road",
    city: "Bethesda",
    zip: "20818",
    coordinates: { lat: 38.9847, lng: -77.1559 },
    courtCount: 2,
    surface: "Dedicated pickleball courts",
    amenities: ["Parking", "Playground"],
    hours: "Sunrise to sunset",
    website: "https://montgomeryparks.org/parks-and-trails/seven-locks-local-park/",
    notes: "Free. Two dedicated courts in the Cabin John area. First come, first served.",
  },

  // ─── Outdoor — free public, mixed (dedicated + striped) ───────────
  {
    slug: "columbia-local-park",
    name: "Columbia Local Park",
    type: "outdoor",
    address: "14900 Old Columbia Pike",
    city: "Burtonsville",
    zip: "20866",
    coordinates: { lat: 39.0837, lng: -76.9436 },
    courtCount: 6,
    surface: "4 dedicated + 2 striped on tennis",
    amenities: ["Parking"],
    hours: "Dawn to dusk",
    website: "https://montgomeryparks.org/parks-and-trails/columbia-local-park/",
    notes: "Free. Renovated 2024. Four dedicated pickleball courts plus two striped on tennis. Burtonsville's primary pickleball facility.",
  },
  {
    slug: "dogwood-park",
    name: "Dogwood Park",
    type: "outdoor",
    address: "800 Monroe Street",
    city: "Rockville",
    zip: "20852",
    coordinates: { lat: 39.0746, lng: -77.1201 },
    courtCount: 5,
    surface: "1 striped on tennis + 4 BYO net",
    amenities: ["Lights", "Parking"],
    hours: "Dawn until 10pm (lighted)",
    website: "https://www.rockvillemd.gov/2313/Pickleball",
    notes: "Free. Lighted — rare for Rockville BYO-net courts. One striped on tennis plus four bring-your-own-net spots.",
  },

  // ─── Outdoor — striped on tennis (free, shared with tennis) ───────
  {
    slug: "argyle-local-park",
    name: "Argyle Local Park",
    type: "outdoor",
    address: "1030 Forest Glen Rd",
    city: "Silver Spring",
    zip: "20901",
    coordinates: { lat: 39.0162, lng: -77.0407 },
    courtCount: 2,
    surface: "Striped on tennis (shared)",
    amenities: ["Lights", "Parking"],
    hours: "Dawn to dusk. Lights available until 11pm.",
    website: "https://montgomeryparks.org/parks-and-trails/argyle-local-park/",
    notes: "Free. Pickleball lines on tennis courts — tennis nets, taller than regulation pickleball. First come, first served.",
  },
  {
    slug: "damascus-recreational-park",
    name: "Damascus Recreational Park",
    type: "outdoor",
    address: "23723 Kings Valley Rd",
    city: "Damascus",
    zip: "20872",
    coordinates: { lat: 39.2811, lng: -77.2017 },
    courtCount: 4,
    surface: "Striped on 2 tennis courts (shared)",
    amenities: ["Lights", "Parking"],
    hours: "Dawn to dusk. Lights available until 11pm.",
    website: "https://montgomeryparks.org/parks-and-trails/damascus-recreational-park/",
    notes: "Free. Damascus's primary pickleball option — striped on tennis. First come, first served.",
  },
  {
    slug: "cannon-road-local-park",
    name: "Cannon Road Local Park",
    type: "outdoor",
    address: "921 Cannon Rd",
    city: "Silver Spring",
    zip: "20904",
    coordinates: { lat: 39.0697, lng: -76.9975 },
    courtCount: 4,
    surface: "Striped on 2 tennis courts (shared)",
    amenities: ["Lights", "Parking"],
    hours: "Dawn to dusk. Lights available until 11pm.",
    website: "https://montgomeryparks.org/parks-and-trails/cannon-road-local-park/",
    notes: "Free. Colesville/Silver Spring border. Pickleball striped on tennis courts.",
  },
  {
    slug: "south-gunners-branch-local-park",
    name: "South Gunner's Branch Local Park",
    type: "outdoor",
    address: "12919 Prairie Knoll Ct",
    city: "Germantown",
    zip: "20874",
    coordinates: { lat: 39.1729, lng: -77.2522 },
    courtCount: 2,
    surface: "Striped on tennis (shared)",
    amenities: ["Parking"],
    hours: "Dawn to dusk",
    website: "https://montgomeryparks.org/parks-and-trails/south-gunners-branch-local-park/",
    notes: "Free. Pickleball striped on tennis. First come, first served.",
  },
  {
    slug: "buck-branch-neighborhood-park",
    name: "Buck Branch Neighborhood Park",
    type: "outdoor",
    address: "8704 Bells Mill Rd",
    city: "Potomac",
    zip: "20854",
    coordinates: { lat: 39.0277, lng: -77.1928 },
    courtCount: 2,
    surface: "Striped on tennis (shared)",
    amenities: ["Lights", "Parking"],
    hours: "Dawn to dusk. Lights available evenings.",
    website: "https://montgomeryparks.org/parks-and-trails/buck-branch-neighborhood-park/",
    notes: "Free. The primary public pickleball option in Potomac proper — striped on tennis.",
  },
  {
    slug: "calverton-galway-local-park",
    name: "Calverton-Galway Local Park",
    type: "outdoor",
    address: "3039 Fairland Rd",
    city: "Silver Spring",
    zip: "20904",
    coordinates: { lat: 39.0692, lng: -76.9645 },
    courtCount: 4,
    surface: "Striped on 2 tennis courts (shared)",
    amenities: ["Parking"],
    hours: "Dawn to dusk",
    website: "https://montgomeryparks.org/parks-and-trails/calverton-galway-local-park/",
    notes: "Free. Pickleball striped on tennis. First come, first served.",
  },
  {
    slug: "diamond-farm-park",
    name: "Diamond Farm Park",
    type: "outdoor",
    address: "857 Quince Orchard Blvd",
    city: "Gaithersburg",
    zip: "20878",
    coordinates: { lat: 39.1349, lng: -77.2136 },
    courtCount: 4,
    surface: "Striped on tennis (shared)",
    amenities: ["Parking"],
    hours: "Dawn to dusk",
    website: "https://www.gaithersburgmd.gov/recreation/parks-fields/diamond-farms-park",
    notes: "Free. Gaithersburg's summer outdoor home for drop-in pickleball — striped on tennis. Court count may vary; verify with city.",
  },

  // ─── Outdoor — Rockville BYO-net (free, bring portable net) ───────
  {
    slug: "welsh-park",
    name: "Welsh Park",
    type: "outdoor",
    address: "344 Martins Lane",
    city: "Rockville",
    zip: "20850",
    coordinates: { lat: 39.0866, lng: -77.1592 },
    courtCount: 6,
    surface: "Striped on tennis (bring your own net)",
    amenities: ["Parking"],
    hours: "Dawn to dusk",
    website: "https://www.rockvillemd.gov/2313/Pickleball",
    notes: "Free. Largest bring-your-own-net pickleball cluster in Rockville — six striped courts on tennis.",
  },
  {
    slug: "civic-center-park",
    name: "Rockville Civic Center Park",
    type: "outdoor",
    address: "603 Edmonston Drive",
    city: "Rockville",
    zip: "20851",
    coordinates: { lat: 39.0809, lng: -77.1445 },
    courtCount: 4,
    surface: "Striped on tennis (bring your own net)",
    amenities: ["Parking"],
    hours: "Dawn to dusk",
    website: "https://www.rockvillemd.gov/2313/Pickleball",
    notes: "Free. Four BYO-net pickleball courts striped on tennis — adjacent to Glenview Mansion.",
  },

  // ─── Outdoor — private clubs / YMCA ───────────────────────────────
  {
    slug: "ymca-bethesda-chevy-chase",
    name: "YMCA Bethesda-Chevy Chase",
    type: "outdoor",
    address: "9401 Old Georgetown Road",
    city: "Bethesda",
    zip: "20814",
    coordinates: { lat: 39.0181, lng: -77.1095 },
    courtCount: 2,
    surface: "Dedicated outdoor pickleball courts",
    amenities: ["Parking", "Restrooms"],
    hours: "Members and drop-in guests — check YMCA schedule",
    website: "https://www.ymcadc.org/pickleball-at-ymca-bethesda-chevy-chase/",
    notes: "YMCA members play free; non-members can drop in for a fee. Bethesda's primary public-access pickleball option.",
  },
  {
    slug: "ymca-silver-spring",
    name: "YMCA Silver Spring",
    type: "outdoor",
    address: "9800 Hastings Drive",
    city: "Silver Spring",
    zip: "20901",
    coordinates: { lat: 39.0258, lng: -77.0319 },
    courtCount: 2,
    surface: "Outdoor pickleball + program clinics",
    amenities: ["Parking", "Restrooms"],
    hours: "Members and guest play — check YMCA schedule",
    website: "https://www.ymcadc.org/locations/ymca-silver-spring/play-pickleball-at-ymca-silver-spring/",
    notes: "YMCA members and guests. Hosts clinics and reservation-based play.",
  },

  // ─── Indoor — county and city rec centers ─────────────────────────
  {
    slug: "bohrer-park-activity-center",
    name: "Activity Center at Bohrer Park",
    type: "indoor",
    address: "506 S Frederick Ave",
    city: "Gaithersburg",
    zip: "20877",
    coordinates: { lat: 39.1376, lng: -77.2003 },
    courtCount: 7,
    surface: "Gymnasium floor",
    amenities: ["Parking", "Restrooms"],
    hours: "Mon/Wed/Fri Oct–May, drop-in play. Check city schedule.",
    website: "https://www.gaithersburgmd.gov/recreation/sports/adult-sports-programs/pickleball",
    notes: "City of Gaithersburg's flagship indoor program — seven pickleball courts on the gym floor. Small drop-in fee for residents and non-residents. The largest year-round indoor program in Montgomery County.",
  },
  {
    slug: "germantown-recreation-center",
    name: "Germantown Recreation Center",
    type: "indoor",
    address: "18905 Kingsview Road",
    city: "Germantown",
    zip: "20874",
    coordinates: { lat: 39.1732, lng: -77.2716 },
    courtCount: 4,
    surface: "Gymnasium floor",
    amenities: ["Parking", "Restrooms", "Water fountain"],
    hours: "Varies by schedule — check MoCo Rec for open play times",
    website: "https://www.montgomerycountymd.gov/montgomery-county-recreation/facilities/recreation-centers/germantown-community-recreation-center",
    notes: "County recreation center. Registration may be required for programs.",
  },
  {
    slug: "long-branch-rec-center",
    name: "Long Branch Community Rec Center",
    type: "indoor",
    address: "8700 Piney Branch Rd",
    city: "Silver Spring",
    zip: "20901",
    coordinates: { lat: 38.9930, lng: -76.9989 },
    courtCount: 2,
    surface: "Gymnasium floor",
    amenities: ["Parking", "Restrooms"],
    hours: "Varies by schedule — check MoCo Rec for open play times",
    website: "https://www.montgomerycountymd.gov/rec/facilities/recreationcenters/longbranch.html",
    notes: "County rec center. Heavily used — Silver Spring's go-to indoor pickleball spot.",
  },
  {
    slug: "praisner-rec-center",
    name: "Marilyn J. Praisner Community Rec Center",
    type: "indoor",
    address: "14906 Old Columbia Pike",
    city: "Burtonsville",
    zip: "20866",
    coordinates: { lat: 39.0953, lng: -76.9263 },
    courtCount: 3,
    surface: "Gymnasium floor",
    amenities: ["Parking", "Restrooms"],
    hours: "Varies by schedule — check MoCo Rec for open play times",
    website: "https://www.montgomerycountymd.gov/rec/facilities/recreationcenters/praisner.html",
    notes: "County rec center. Three indoor pickleball courts — uncommon for MoCo rec centers. Burtonsville's indoor option.",
  },
  {
    slug: "mid-county-rec-center",
    name: "Mid-County Community Rec Center",
    type: "indoor",
    address: "2004 Queensguard Road",
    city: "Silver Spring",
    zip: "20906",
    coordinates: { lat: 39.0675, lng: -77.0563 },
    courtCount: 2,
    surface: "Gymnasium floor",
    amenities: ["Parking", "Restrooms"],
    hours: "Varies by schedule — check MoCo Rec for open play times",
    website: "https://www.montgomerycountymd.gov/rec/facilities/recreationcenters/midcounty.html",
    notes: "County rec center in the Layhill/Aspen Hill area. Indoor pickleball available — verify open play schedule.",
  },
  {
    slug: "white-oak-rec-center",
    name: "White Oak Community Rec Center",
    type: "indoor",
    address: "1700 April Lane",
    city: "Silver Spring",
    zip: "20904",
    coordinates: { lat: 39.0428, lng: -76.9886 },
    courtCount: 2,
    surface: "Gymnasium floor",
    amenities: ["Parking", "Restrooms"],
    hours: "Varies by schedule — check MoCo Rec for open play times",
    website: "https://www.montgomerycountymd.gov/rec/facilities/recreationcenters/",
    notes: "County rec center. Verify open play schedule and court count via MoCo Rec.",
  },
  {
    slug: "plum-gar-rec-center",
    name: "Plum Gar Community Rec Center",
    type: "indoor",
    address: "19561 Scenery Drive",
    city: "Germantown",
    zip: "20876",
    coordinates: { lat: 39.1815, lng: -77.2570 },
    courtCount: 2,
    surface: "Gymnasium floor",
    amenities: ["Parking", "Restrooms"],
    hours: "Varies by schedule — check MoCo Rec for open play times",
    website: "https://www.montgomerycountymd.gov/rec/facilities/recreationcenters/",
    notes: "County rec center. Germantown's secondary indoor option — verify schedule via MoCo Rec.",
  },
  {
    slug: "bauer-drive-rec-center",
    name: "Bauer Drive Community Rec Center",
    type: "indoor",
    address: "14625 Bauer Drive",
    city: "Rockville",
    zip: "20853",
    coordinates: { lat: 39.0925, lng: -77.1215 },
    courtCount: 2,
    surface: "Gymnasium floor",
    amenities: ["Parking", "Restrooms"],
    hours: "Varies by schedule — check MoCo Rec for open play times",
    website: "https://www.montgomerycountymd.gov/rec/facilities/recreationcenters/",
    notes: "County rec center co-located with Bauer Drive Local Park's outdoor courts. Verify indoor schedule via MoCo Rec.",
  },
  {
    slug: "wheaton-indoor-tennis",
    name: "Wheaton Indoor Tennis",
    type: "indoor",
    address: "11715 Orebaugh Avenue",
    city: "Wheaton",
    zip: "20902",
    coordinates: { lat: 39.0639, lng: -77.0498 },
    courtCount: 6,
    surface: "Indoor tennis bays striped for pickleball",
    amenities: ["Parking", "Restrooms"],
    hours: "Mon/Wed/Fri 2–4pm pickleball window. Reserve in advance.",
    website: "https://montgomeryparks.org/parks-and-trails/wheaton-regional-park/indoor-tennis-facility/",
    notes: "Three tennis bays striped for pickleball during designated windows. Hourly court rental — up to 8 players per court. Wheaton's primary indoor option until the Rubini outdoor project completes (currently in design phase).",
  },
];

export function getCourtBySlug(slug: string): Court | undefined {
  return courts.find((c) => c.slug === slug);
}

export function getFeaturedCourts(): Court[] {
  return courts.filter((c) => c.featured);
}
